# Generated by Django 6.0.2 on 2026-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valentines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valentine',
            name='recipient_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='valentine',
            name='sender_name',
            field=models.CharField(max_length=100),
        ),
    ]
