# Generated by Django 6.0.2 on 2026-02-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valentines', '0002_alter_valentine_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valentine',
            name='recipient_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='valentine',
            name='sender_name',
            field=models.CharField(max_length=120),
        ),
    ]
